### PR TITLE
Fixes 2 breasts-related functions

### PR DESCRIPTION
**Pull request by Terridan**
hasCuntNipples() was only ever returning the result for the first row.
Also, since the result of these functions is a boolean, we don't need to
run the entire loop and can just return on the first success.

### CODE REVIEW

**Comment by Fenoxo** [comment]
So the top one looks like it just fixes some slight overcomplications of functions that work fine.

Not sure what's going on in that bottom merge though, looks like it's messing with Geddy's damage code.

**Comment by tmedwards** [comment]
The commits look stupid because they created the PR relative to their master, rather than creating a branch specifically for the fix.  If you check the *Files changed* tab, you should see that relative to (the current) *Fexono:master* their PR only modifies the two functions in `Creature.as`.

Beyond that, while the modification to `hasFuckableNipples()` is merely a simplification, the modification to `hasCuntNipples()` is indeed a bugfix.  In the original code, the `if` statement after the `while` loop erroneously uses `counter` again, rather than the `index` of the found nipples, so that only the first row is actually checked with regards to the returned value.

I'm unsure if it's possible in-game to acquire nipple cunts on lower breast rows, while not also having them on the uppermost, so the bug may not be triggerable normally, but it can't hurt to fix it.

**Comment by Terridan** [comment]
Yes, I messed up with the git, only the top one is relevant and was posted as sort of "test PR". Having a month+ long wait to even look at them does a lot to disincentivize the use of this approach.

**Comment by Fenoxo** [comment]
Fair enough. I definitely need to get better at keeping up on the ol' 'hub.

**Pull request merged**
