### PR TITLE
[cockLongest] parser tag and Sera.

### PR DESCRIPTION
**Pull request by noobsaleh**

### CODE REVIEW

**Comment by Fenoxo** [comment]
1. Create pull request with absolutely no description and a huge amount of changes to sera's file.
2. ????
3. Profit

**Comment by noobsaleh** [comment]
My bad; it's Nonesuch's first expansion for Sera.

**Comment by noobsaleh** [comment]
Just wondering if you had a chance to look over this yet?

**Comment by mijhy** [comment]
@noobsaleh very large pull requests are not fun to review.

**Comment by Murphy540** [comment]
You need to escape all of your quotes. It's really not at all in a state ready to be applied.

@noobsaleh Recommend: closing this pull request, updating your working directory, setting up an IDE and try compiling it yourself. I'm guessing you're going to get hundreds of errors and warnings.

**Comment by noobsaleh** [comment]
Nah, they're non-standard quotes so they don't need to be escaped. I always compile and test on my own; it works perfectly and I wouldn't have submitted a pull request otherwise.

Also, I'm sure they have a script for standard quotes.

**Comment by Murphy540** [comment]
Pulling it into mine, it compiles fine. I still think you should've gone with a bunch of smaller commits rather than adding it all at once. i.e. one commit for each scene or so...


You've missed a few things here and there, though. A [boy] when you need a [pc.boy], [he] when you need [pc.he]. Stuff like that.

Looking over Nonesuch's docs... the inch-stealing doesn't follow the logic correctly. Try subbing Sera >=12, shrinking it below 12 with condensol, then going back when it wears off. Things... don't exactly go as planned.

**Comment by herp-a-derp** [comment]
Please, please, PLEASE don't use fucking fancy-quotes. They can make refactoring or reworking a complete disaster.

The text engine automatically "prettifies" normal quotes at runtime, as part of it's display rendering.

**Comment by noobsaleh** [comment]
@Murphy540: I mean, doing one commit per scene would have had me submitting multiple commits per day. Wouldn't that have caused more frustration than good? Also, I believe tags like [boy] and [he] don't use the pc as a pointer because they assume it by default (unlike tags like cockLongest, which require a reference to work properly). Are you saying "[boy]" shows up in the text after compiling rather than either "boy" or "girl"? Again, I apologize as it works fine for me.

As for the logic, I changed it slightly from the doc (with permission from Nonesuch). What exactly is the issue happening?


@herp-a-derp: I apologize; Nonesuch told me that non-standard quotes were fine when I asked him so I just included them when copying and pasting from his doc.

**Comment by herp-a-derp** [comment]
noobsaleh - Primarily, they're confusing, they're not ASCII (so some text editors shit on them), and most importantly, *why*?

In general, it's probably best to keep the source as pure-ASCII as possible. Once you venture out into additional codepages, things can get shitty fast.  
If you stick to UTF-8, it's generally *better*, but you can still break shit for people running with their computer set to a different language.

**Comment by Fenoxo** [comment]
Eh, Gedan has a macro that formats prettyquotes with italic markup properly
for me, so I've been working with prettyquotes for writing stuff as of
late, even if it does make it impossible to slip any proper code into a
scene.

**Comment by herp-a-derp** [comment]
Uh.... you do know I'm pretty sure I implemented auto-pretty-quote in the parser like a year ago, right?

**Comment by Murphy540** [comment]
The reason you do one commit per scene is that you must thoroughly test each scene to make sure stuff like the Inch Stealing scene doesn't trigger twice on the first go around...

**Comment by noobsaleh** [comment]
The way Nonesuch's doc is organized you have to go back and edit past scenes a lot to connect the subsequent ones. Anyway, I must be doing something stupid because I'm having difficulty recreating the issue; I'll take a closer look soonish.

**Comment by Murphy540** [comment]
I'll see if I can get a save right at the trouble spot ready for you to test...

**Comment by Fenoxo** [comment]
The auto pretty-quote wasn't actually working 100%. Easier to just press a
couple keys in sublime text and have it be good to go.

**Comment by noobsaleh** [comment]
Just to clarify, the bug is just repeated text, right, nothing too serious? I'll take a look at it asap.

**Comment by Fenoxo** [comment]
I try to avoid the combined ellipses symbol, honestly.

That variable pass should work fine.

**Comment by Gedan** [comment]
@herp-a-derp Insertion of prettyquotes was just something I tacked on to the end of a Sublime macro that was already doing a bunch of other shit anyway. If nothing else it makes the scene source slightly easier to read.

**Pull request closed without merging**
