### PR TITLE
Fixed some more Lane gender tags

### PR DESCRIPTION
**Pull request by braincoral**
I fixed several gender tags for Lane.

### CODE REVIEW

**Comment by braincoral** [comment]
This pull request also fixes most of the issues listed in issue #269. Other than the "as you remember it" thing, which would probably require a new tag to check if it's the first time PC has been hypnotized.

**Comment by braincoral** [comment]
Also really not sure why it seems to think line 1 was modified, since it's exactly the same, but whatever I guess.

**Comment by tmedwards** [comment]
They aren't exactly the same.  The original file does not include the UTF-8 fake BOM, yours does.  That's the difference.

**Comment by braincoral** [comment]
Ah, I see. I forgot to change the character encoding. I fixed it, BOM removed.

**Comment by Gedan** [comment]
[Variable Gender Character Hatred Intensifies]

**Pull request merged**
